### PR TITLE
fix to detect states that have more than 1 word (eg new york)

### PR DESCRIPTION
**Pull request by catalint**
Multiple word states were not detected , fixed & added tests

### CODE REVIEW

**Comment by markstos** [comment]
Thanks for including the tests. Looks good. Merging.

**Comment by markstos** [comment]
@catalint, perhaps you'd be interested in being a co-maintainer? 

The original author has over 200 packages published and has limited time. He made me a co-maintainer, but I don't actually use this anymore. I use the [contact-parser](https://www.npmjs.com/package/contact-parser) module instead. 

 @DamonOehlman would have to approve and give you access if you are interested.

**Comment by catalint** [comment]
sure, let me know expectations / how I can help

**Comment by markstos** [comment]
@DamonOehlman this developer just submitted a nicely structured and commented PR with tests included. OK to add him a direct committer?

**Comment by DamonOehlman** [comment]
Sounds good to me - I'll make that happen :)

**Comment by DamonOehlman** [comment]
@catalint you now have committer access :)

**Comment by markstos** [comment]
@DamonOehlman great. Do you want to still do the npm uploads or share that as well?

**Comment by DamonOehlman** [comment]
@markstos @catalint Happy to share that too - I think as long as people have a bit of an understanding around semantic versioning then I'm happy to add them on authors on npm also :)

**Comment by markstos** [comment]
Quick reference for semantic versioning:

Given a version number MAJOR.MINOR.PATCH, increment the:

* MAJOR version when you make incompatible API changes,
* MINOR version when you add functionality in a backwards-compatible manner, and
* PATCH version when you make backwards-compatible bug fixes.

Details: http://semver.org/

**Pull request merged**
